### ISSUE TITLE
7.0.0 roadmap

### ISSUE THREAD

**Issue by jasonmit** [stefanpenner/ember-moment#163]
This list will likely grow.

* [x] drop `LLLL` as default format See: #162 
  * [ ] Needs documentation explaining breaking change and work around
* [x] bump deps
* [x] add/subtract moment methods exposed as helpers
* [x] query methods as helpers (isSame, isBefore, isAfter, etc.)
```hbs
{{#if (is-before '2010-10-21' (now))}}
  Time-enabled feature
{{/if}}
```

**Comment by yads** [comment]
I'm looking to implement the add/subtract functionality. Any thoughts on which version of add/subtract to implement. I was thinking of something like:

```
{{moment-add date 1 precision="year"}}
{{moment-add date durationObj}}      <!-- durationObj could be like {year: 1, month: 6} -->
```

Thoughts?

**Comment by yads** [comment]
See #181 for add/subtract functionality

**Comment by jasonmit** [comment]
Supporting both of those APIs seems appropriate, thanks

**Comment by yads** [comment]
@jasonmit I just realized that add/subtract mutate the original value. I'm guessing the intent of the add/subtract helpers is to not mutate any of the values passed to the helper.

**Comment by jasonmit** [comment]
@yads if `moment.add` mutates instead of returns a new instance of an moment object, then I would expect the helper to do the same.  I think it's safe to keep the way it currently is.

**Comment by yads** [comment]
Currently there is no way to clone a value, which could lead to problems. I don't think people would expect the following to modify their model:

```
{{moment-add model.createdAt 1 precision='days'}}
```

**Comment by jasonmit** [comment]
In the example above, is `createdAt` a moment object?

For mutability, we could support `{{moment-add (mut model.createdAt) 1 'days'}}` vs `{{moment-add model.createdAt 1 'days'}}` which would clone `Date` or `moment` objects before doing the addition.

It hasn't been versioned yet, so we can make whatever changes necessary.

**Comment by yads** [comment]
Actually forget I said anything. I completely forgot that we're already wrapping any input in a moment call which will clone a moment object. I think we're good to go from that standpoint.

https://github.com/stefanpenner/ember-moment/blob/1ed9a81b630303dd5c1ed298329ad2f36f8510af/addon/helpers/moment-add.js#L26

**Comment by jasonmit** [comment]
@yads sounds good, I'll write some tests around this to validate & prevent regressions

**Comment by spovich** [comment]
Is there a plan for a minimum ember version supported for 7.0?  I was trying to cleanup old dependencies and when I removed `ember-getowner-polyfill` I got this ```Could not find module `ember-getowner-polyfill` imported from `ember-moment/computeds/format````  The get owner stuff is baked into ember 2.3 and later.

**Comment by jasonmit** [comment]
@spovich I would think we will support down to 1.13 like we have been.  If you want to work on removing the dependency on `ember-getowner-polyfill` I'd be happy to accept a PR for it.

**Comment by jasonmit** [comment]
```js
// addon/utils/get-owner.js
import Ember from 'ember';

let getOwner = Ember.getOwner;

if (typeof getOwner !== 'function') {
  try {
    getOwner = require('ember-getowner-polyfill')['default'];
  }
  catch(e) {
    Ember.Logger.error('getOwner API unsupported.  To resolve this: `ember install ember-getowner-polyfill`');
  }
}

export default getOwner;
```

This is kind of pseudo-code, but it could give you an idea how we could support the older and newer versions w/o adding `ember-getowner-polyfill` as a direct dep. of `ember-moment`.

**Comment by jasonmit** [comment]
@spovich fixed on master, waiting to version as 7.0.0-stable

**Comment by spovich** [comment]
@jasonmit nice! Thank you!
